- name: Deploiement d'une application Flask avec Docker
  hosts: all
  become: yes
  tasks:

    # 0. Pre-requis (création du groupe docker)
    - name: Verifier et creer le groupe docker si nécessaire
      become: yes
      group:
        name: docker
        state: present

    - name: Ajouter utilisateur distant au groupe
      become: yes
      user:
        name: "distant"
        groups: docker
        append: yes

    - name: Redemarrer Docker pour appliquer les changements
      become: yes
      systemd:
        name: docker
        state: restarted

    # 1. Installer Docker
    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    # 2. Créer le répertoire de l'application
    - name: Creer le répertoire de application sur le serveur
      file:
        path: /home/distant/app
        state: directory

    # 3. Copier tous les fichiers necessaires (Dockerfile, requirements.txt) sur le serveur distant
    - name: Copier le Dockerfile et les fichiers necessaires sur le serveur distant
      copy:
        src: /home/projet_ansible_docker/docker
        dest: /home/distant/app/docker
        owner: distant
        group: distant
        mode: '0755'
        remote_src: no

    # 4. Construire image Docker à partir du Dockerfile
    - name: Constuire image Docker
      command: docker build -t mon_flask_app /home/distant/app/docker

    # 5. Lancer le conteneur Docker
    - name: Lancer le conteneur Docker
      command: docker run -d -p 5000:5000 mon_flask_app


